services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_INTERNAL_HOSTNAME: kafka
      KAFKA_LISTENER_NAME_EXTERNAL: OUTSIDE
      KAFKA_LISTENER_PORT: 9092
      KAFKA_ADVERTISED_LISTENER_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_EXTERNAL_PORT: 9092
      KAFKA_LISTENER_EXTERNAL_HOSTNAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
